### ISSUE TITLE
Wilderness player alarm only showing on a section of the screen.

### ISSUE THREAD

**Issue by PeachT17** [adhansen/wilderness-player-alarm#46]
It's only on the bottom right of my screen, entirely hidden if im on fixed classic mode and behind my inventory mainly if I'm using another.
![edc88e0233](https://github.com/user-attachments/assets/6cc4bf8d-3971-4872-b024-d10c0243939f)

**Comment by adhansen** [comment]
I haven't been able to reproduce this. I can see from your sidebar that you have a lot of external plugins installed, far more than I have & test with on my client. I suspect it's an interoperability issue with another hub plugin. If you're up for helping to root cause this, you could toggle your plugins on & off individually while using the alarm somewhere that it's easy to set it off (IE PVP world GE) and figure out which one produces this interaction.

**Comment by PeachT17** [comment]
I've tried turning every toggleable plugin off and am having the same issue, it doesn't occur when I create a brand new profile however.

**Comment by adhansen** [comment]
>  it doesn't occur when I create a brand new profile

Okay, well that's a promising lead.
You could try duplicating your main profile and _resetting_ plugins one-by-one instead of just toggling them to narrow it down. I wouldn't recommend doing this without duping the profile as it will destroy plugin configurations that may be tedious or impossible to get back without a backup.

**Comment by muggleosrs** [comment]
this exact same thing is happening to me, it was out of no where and no plugin or settings changes were made. i too have gone through my entire list of plugins and it doesnt seem to matter 

EDIT, i just uninstalled every single external plugin and turned off every single runelite plug except for wilderness player alarm and it did not fix this issue. seems to me we will have to create new profiles and try to set up the profile to match previous one...

**Comment by 3Dpoo** [comment]
Having the same issue, creating a new profile fixes it, but that's less than an ideal solution

**Comment by adhansen** [comment]
Hmm okay, thanks for taking the time to help investigate this. There have been a few compatibility issues since bringing back the flashing (this and #42), and one thing that has changed in the new implementation is the addition of this line:
https://github.com/adhansen/plugin-repo/blob/WildernessPlayerAlarm/release/src/main/java/com/WildernessPlayerAlarm/AlarmOverlay.java#L20

I like `OverlayLayer.ABOVE_SCENE` because as opposed to the initial implementation of this plugin, it causes the flashing to render behind the GUI layers with the inventory, chat, minimap, and other widgets. Previously, it would tint your inventory which I think is not great for usability. Here is an example of the current implementation versus the alternative using `OverlayLayer.ALWAYS_ON_TOP`


![above_scene](https://github.com/user-attachments/assets/8f82afc7-4055-4b41-bfd3-effdd6b5c316)


![always_on_top](https://github.com/user-attachments/assets/85bfcb93-0f93-4f38-ab25-d159011320e0)


Unfortunately I can't reproduce either of these issues but I'm beginning to suspect this is root cause. For instance, in #42 the issue was reported with the ping grapher which is also rendered on the `ABOVE_SCENE` layer: https://github.com/yuh25/Ping-Grapher/blob/master/src/main/java/com/pinggraph/PingGraphOverlay.java#L49

If anyone who is able to reproduce this issue and run the project built from source is willing to further help, I would be interested to see if this patch fixes the issue: 
[layerpatch.patch](https://github.com/user-attachments/files/17853075/layerpatch.patch)

Another thing to consider is that even if it does, it might not be worth releasing. I have zero insight into how many people are experiencing these overlay issues versus how many people would be upset over the overlay covering more of the client with such a fix. Maybe the layer would have to be set by a config option, like the ping grapher also does.

> creating a new profile fixes it

Does resetting the plugin fix it?

**Comment by 3Dpoo** [comment]
Resetting the plugin does nothing. My assumption on the issue was the flashing box was moved using the alt+left click, and dragged to a different spot, which is why it might have pushed other interfaces from the top left down,  I've had this issue before with the Alarm pushing down my clue hint box from the top left into the bottom left.

[Sad Bug - Default.txt](https://github.com/user-attachments/files/17853458/Sad.Bug.-.Default.txt)

I've attached my profile export, maybe you can use it to recreate the issue in this thread, just rename it from .txt to .properties

**Comment by adhansen** [comment]
Thanks @3Dpoo I was able to repro with that profile (after pulling 12MB of plugins the first time I tried to use it lmao). I think I have a fix as well. Need to test it more comprehensively but stay tuned!

**Comment by PeachT17** [comment]
Sorry to be a pest but is there any news on the fix to this?

**Comment by adhansen** [comment]
Sorry I've been binging leagues since release but I'm super burnt-out on it now. I'll finish testing this and get it into PR on the hub this weekend.
